secret:
  ignored-matches:
  - match: 1548bf7d20ea4a49e7580b83285c6e3f13bd9104ffeafd058e8e32d2beeee651
    name: PostgreSQL Credentials - /Users/m.zakiyuddinmunziri/Code/JS/NextJS/2024/sirekap/pages/index.mdx
  - match: 586f915c6621ee4a0d3f24f307685779cb9dfe2ed9546f61be3299f5a464b56b
    name: PostgreSQL Credentials - /Users/m.zakiyuddinmunziri/Code/JS/NextJS/2024/sirekap/pages/index.mdx
  - match: 23046ce2ff764752813ef787e0c89aebda3ba728fab942df20b984d6a8cbd651
    name: PostgreSQL Credentials - /Users/m.zakiyuddinmunziri/Code/JS/NextJS/2024/sirekap/pages/index.mdx
version: 2
